name: Build Master

on:
  push:
    branches:
    - master-test

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build Production
        run: |
          yarn install
          yarn build-production-client
          yarn build-production-php
          yarn build-extensions
          gulp languages:extract
      - name: Purge dev files
        run: echo "Purge dev files"
      - name: Commit and push to built branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout master-test-built
          git commit -am "Update master built" 
          git push
          
