name: Build production to master-built
on:
  push:
    branches:
      - test-it

jobs:
  build_master_job:
    runs-on: ubuntu-latest
    name: Build production version of master to master-built branch
    steps:
#      - name: Checkout Jetpack
#        uses: actions/checkout@master
      - name: Build and push to built branch
        uses: automattic/action-jetpack-build-to-branch@testing
        with:
          branch_pull: 'test-it'
          branch_push: 'test-it-built'
          commit_message: 'Automated production build from master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
