name: Build production to master-built
on:
  push:
    branches:
      - test-it

jobs:
  build_master_job:
    runs-on: ubuntu-latest
    name: Build production version of master to master-built branch
    steps:
      - name: Push to built branch
        id: commit-and-push
        uses: automattic/action-jetpack-build-to-branch@master
        with:
          branch_pull: 'test-it'
          branch: 'test-it-built'
          commit_message: 'Automated production build from test-it'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
