name: Build Master

on:
  push:
    branches:
    - master-test

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Build Production
        run: |
          git checkout git@github.com:dereksmart/jetpack.git
          yarn build-production
