name: Build Master

on:
  push:
    branches:
    - master-test

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build Production
        run: |
          yarn install --production
          yarn build-production-client
          yarn build-production-php
      - name: Build Extensions
        run: NODE_ENV=production yarn build-extensions
      - name: Extract languages
        run: gulp languages:extract
          
