name: Build Master

on:
  push:
    branches:
    - master-test

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
          with:
            fetch-depth: 1
      #- name: Build Production
      #  run: |
      #    yarn install
      #    yarn build-production-client
      #    yarn build-production-php
      #    yarn build-extensions
      #    gulp languages:extract
      - name: Purge dev files
        # Just an example, we'll want to remove all of the .svnignore files
        run: rm ./.eslintrc.js
      - uses: bumfo/action-deploy@v1
        with:
          ref: 'refs/heads/master-test-built'  # The branch to auto deploy, default to release/snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
