name: Build Master

on:
  push:
    branches:
    - master-test

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install deps
        run: yarn install
      - name: Build Production
        run: |
          yarn clean
          yarn install --production
          yarn build-production-client
          yarn build-production-php
          NODE_ENV=production yarn build-extensions
          gulp languages:extract
          
