name: Build Master

on:
  push:
    branches:
    - master-test

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@1.1.0
        run: yarn build-production
