name: Hello
on:
  push:
    branches:
      - hello-world

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Do something
        id: do-something
        uses: dereksmart/action-playground@master
        with:
          branch: 'hello-world-built'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"