name: Build production to master-built
on:
  push:
    branches:
      - hello-world

jobs:
  build_master_job:
    runs-on: ubuntu-latest
    name: Build production version of master to master-built branch
    steps:
      - name: Checkout Jetpack
        uses: actions/checkout@master
      - name: Build production files
        run: rm $GITHUB_WORKSPACE/.eslintrc.js
#        run: |
#          yarn install
#          yarn build-production-client
#          yarn build-production-php
#          yarn build-extensions
#          gulp languages:extract
      - name: Purge dev files
        run: $GITHUB_WORKSPACE/bin/prepare-built-branch.sh
      - name: Push to built branch
        id: commit-and-push
        uses: automattic/action-commit-to-branch@initial-commit
        with:
          branch: 'whatever-built3'
          commit_message: 'Automated production build from master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}