name: Do something!
on:
  push:
    branches:
      - hello-world

jobs:
  build_master_job:
    runs-on: ubuntu-latest
    name: Build to master-built
    steps:
      - name: Checkout Jetpack
        uses: actions/checkout@master
      - name: Build production files
        # todo fix the actual production build command, this should just be 'yarn build-production'
        run: rm .sass-cache
#        run: |
#          yarn install
#          yarn build-production-client
#          yarn build-production-php
#          yarn build-extensions
#          gulp languages:extract
      - name: Purge dev files
        run: $GITHUB_WORKSPACE/bin/purge-dev-files.sh
      - name: Push to built branch!
        id: commit-and-push
        uses: dereksmart/action-playground@master
        with:
          branch: 'hello-world-built'
          commit_message: 'Build master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}